; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nodemcu-32s

[env]
framework = arduino
build_flags =
    -D CLI_COMMANDS_MAX=25
    -D CLI_PROMPT="\"\\033[1;32mcliDemo$ \\033[0m\""
; Use the line below to control libCli features for ressource usage tests.
;    -D RESOURCE_USAGE_TEST
;    -D CLI_HISTORYSIZ=200
;    -D CLI_TAB_COMPLETION=0
lib_deps =  
    https://github.com/fjulian79/libversion.git#main
    https://github.com/fjulian79/libgeneric.git#main
    https://github.com/fjulian79/libcli.git#main
;   fjulian79/libCli @ ^4.6.0
lib_ldf_mode = deep
monitor_speed = 115200

[env:nucleo_f103rb]
platform = ststm32
board = nucleo_f103rb
monitor_filters = direct

[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
monitor_filters = direct

[env:nodemcu]
platform = espressif8266
board = nodemcu
monitor_filters = direct

[env:esp-01]
platform = espressif8266
board = esp01
upload_resetmethod = nodemcu
monitor_filters = direct

[env:esp-01s]
platform = espressif8266
board = esp01_1m
upload_resetmethod = nodemcu
monitor_filters = direct

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
monitor_filters = esp32_exception_decoder
;debug_tool = jlink
;debug_init_break = tbreak setup
;debug_speed = 2000 ;kHz

[env:lolin_d32]
platform = espressif32
board = lolin_D32
monitor_filters = esp32_exception_decoder

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
monitor_filters = esp32_exception_decoder

[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
monitor_filters = esp32_exception_decoder

[env:esp32-c6-super-mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c6-devkitm-1
monitor_filters = esp32_exception_decoder

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_filters = direct
